---
apiVersion: v1
kind: Namespace
metadata:
  name: kapture
  labels:
    name: kapture
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kapture
  namespace: kapture
  labels:
    kubernetes.io/cluster-service: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kapture
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kapture
  labels:
    kubernetes.io/cluster-service: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kapture
subjects:
- kind: ServiceAccount
  name: kapture
  namespace: kapture
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kapture
  namespace: kapture
data:
  CAPTURE_PODS: "app=kapture-node"
  CAPTURE_PODS_NAMESPACE: "kapture"
  NODE_API: "127.0.0.1:9091"
  NODE_API_PORT: "9090"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kapture-api
  namespace: kapture
  labels:
    app: kapture-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kapture-api
  template:
    metadata:
      labels:
        app: kapture-api
    spec:
      serviceAccountName: kapture
      containers:
      - name: kapture
        image: registry-ci.at4d.liacloud.com/devops/kapture-api:0.2.12
        ports:
        - containerPort: 9090
        envFrom:
        - configMapRef:
            name: kapture
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
# ---
# #ALLOW EGRESS, DENY ALL INGRESS
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  annotations:
  name: default-deny
  namespace: kapture
spec:
  podSelector: {}
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: kapture-api
  namespace: kapture
spec:
  podSelector:
    matchLabels:
      app: kapture-api
  ingress:
  - from: []
