---
apiVersion: v1
kind: Namespace
metadata:
  name: kapture
  labels:
    name: kapture
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kapture
  namespace: kapture
  labels:
    kubernetes.io/cluster-service: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kapture
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kapture
  labels:
    kubernetes.io/cluster-service: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kapture
subjects:
- kind: ServiceAccount
  name: kapture
  namespace: kapture
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kapture
  namespace: kapture
data:
  CAPTURE_PODS: "app=kapture-node"
  CAPTURE_PODS_NAMESPACE: "kapture"
  NODE_API_PORT: "10000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kapture-api
  namespace: kapture
  labels:
    app: kapture-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kapture-api
  template:
    metadata:
      labels:
        app: kapture-api
    spec:
      serviceAccountName: kapture
      containers:
      - name: kapture
        image: spirrello/kapture-api:0.1.6
        ports:
        - containerPort: 9090
        envFrom:
        - configMapRef:
            name: kapture
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: kapture-api
  namespace: kapture
spec:
  selector:
    app: kapture-api
  ports:
  - name: http
    protocol: TCP
    port: 9090
---
# #ALLOW EGRESS, DENY ALL INGRESS
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  annotations:
  name: default-deny
  namespace: kapture
spec:
  podSelector: {}
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: kapture-api
  namespace: kapture
spec:
  podSelector:
    matchLabels:
      app: kapture-api
  ingress:
  - from: []
