---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kapture-node
  namespace: kapture
  labels:
    app: kapture-node
spec:
  selector:
    matchLabels:
      app: kapture-node
  template:
    metadata:
      labels:
        app: kapture-node
    spec:
      volumes:
      - name: pcap
        emptyDir: {}
      hostNetwork: true
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: kapture-node
        image: spirrello/kapture-node:0.1.6
        envFrom:
        - configMapRef:
            name: kapture
        ports:
        - containerPort: 10000
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        volumeMounts:
        - mountPath: /pcap
          name: pcap
      terminationGracePeriodSeconds: 5
# ---
# apiVersion: extensions/v1beta1
# kind: NetworkPolicy
# metadata:
#   name: kapture-node-default-deny
#   namespace: kapture
# spec:
#   podSelector:
#     matchLabels:
#       app: kapture-node
#   ingress: []
# ---
# apiVersion: extensions/v1beta1
# kind: NetworkPolicy
# metadata:
#   name: kapture-node
#   namespace: kapture
# spec:
#   podSelector:
#     matchLabels:
#       app: kapture-node
#   ingress:
#   #FOR TEST PURPOSES ONLY
#   #- from: []
#   #Commenting out for now while we test
#   - from:
#       - podSelector:
#           matchLabels:
#             app: kapture-api

