---
apiVersion: v1
kind: Namespace
metadata:
  name: kcapture
  labels:
    name: kcapture
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kcapture
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kcapture
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kcapture
  labels:
    kubernetes.io/cluster-service: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kcapture
subjects:
- kind: ServiceAccount
  name: kcapture
  namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kcapture
data:
  CAPTURE_PODS: "name=kcapture-node"
  CAPTURE_PODS_NAMESPACE: "kube-system"
  NODE_API: "127.0.0.1:9091"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcapture-api
  namespace: kube-system
  labels:
    app: kcapture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kcapture-api
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kcapture-api
    spec:
      serviceAccountName: kcapture
      containers:
      - name: kcapture
        image: registry-ci.at4d.liacloud.com/devops/kcapture-api:0.1.0
        ports:
        - containerPort: 9090
        envFrom:
        - configMapRef:
            name: kcapture
      resources:
      requests:
        memory: "128i"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"
